remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

buttons:
  zip_url: https://github.com/tuur29/pages-themes-cayman
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true
