title: My Jekyll Site
description: A demo Jekyll static site with Architect theme and menu buttons
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

include:
  - _includes/head-custom.html
  - _includes/nav.html
