title: RajeshSadashiva
description: Multi-Cloud Architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

include:
  - _includes/head-custom.html
  - _includes/nav.html

{% include nov.md %}
