remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  
nav:
  - name: "View on GitHub"
    url: "https://github.com/yourusername/yourrepo"
  - name: "About"
    url: "/about.html"
  - name: "Contact"
    url: "/contact.html"
