remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Add this line to include your custom head file
include:
  - _includes/head-custom.html

# (your nav remains unchanged)
nav:
  - name: "View on GitHub"
    url: "https://github.com/yourusername/yourrepo"
  - name: "About"
    url: "/about.html"
  - name: "Contact"
    url: "/contact.html"
